export const BUSINESS_CATEGORIES = [
  { value: "fashion_apparel", label: "Fashion & Apparel" },
  { value: "footwear", label: "Footwear" },
  { value: "accessories", label: "Accessories & Jewelry" },
  { value: "beauty", label: "Beauty & Cosmetics" },
  { value: "home_decor", label: "Home & Decor" },
  { value: "electronics", label: "Electronics" },
  { value: "grocery", label: "Grocery & Convenience" },
  { value: "other", label: "Other retail" },
] as const;

export const COUNTRIES = [
  { value: "IN", label: "India" },
  { value: "AE", label: "United Arab Emirates" },
  { value: "SG", label: "Singapore" },
  { value: "GB", label: "United Kingdom" },
  { value: "US", label: "United States" },
] as const;

export const INDIAN_STATES = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
] as const;